name: flutter_bloc_widget
description: an experimental Flutter package that provides a new way to build widgets in Flutter applications using the BLoC (Business Logic Component) pattern.
version: 0.0.1-alpha
homepage: https://github.com/Yczar/flutter-bloc-widget

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: any

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
